apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-server
  namespace: demo
  labels:
    app: web
spec:
  replicas: 5
  # strategy:
  #   type: Recreate # default is RollingUpdate
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: front-end
          image: basic-node-server:0.0.3
          ports:
            - containerPort: 80
          resources:
            # You must specify requests for CPU to autoscale
            # based on CPU utilization
            # requests:
            #   cpu: "250m"
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      # imagePullSecrets:
      #   - name: regcred
