---
apiVersion: v1
kind: Pod
metadata:
  name: basic-server
  namespace: demo
  labels:
    app: web
spec:
  containers:
    - name: front-end
      image: basic-node-server:0.0.2
      imagePullPolicy: Never # stops it pulling from remote
      readinessProbe:
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 30
      livenessProbe:
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds: 5
        timeoutSeconds: 2
        periodSeconds: 30
        failureThreshold: 1
      ports:
        - containerPort: 80
  # imagePullSecrets:
  #   - name: regcred
---

